const {
  NEXT_PUBLIC_FILE_VISIT_URL: FILE_URL,
  NEXT_PUBLIC_BASE_URL: DOMAIN,
  NEXT_PUBLIC_HOSTNAME: HOSTNAME,
  ADMIN_ID: _ADMIN_ID,
  RENDER_MODE: _RENDER_MODE,
  SERVER_URL: _SERVER_URL
} = process.env;

export { FILE_URL, DOMAIN, HOSTNAME, _ADMIN_ID, _RENDER_MODE, _SERVER_URL };
