const {
  NEXT_PUBLIC_FILE_VISIT_URL: FILE_URL,
  NEXT_PUBLIC_BASE_URL: DOMAIN,
  NEXT_PUBLIC_HOSTNAME: HOSTNAME,
  ADMIN_ID: _ADMIN_ID,
  RENDER_MODE: _RENDER_MODE,
  SERVER_URL: _SERVER_URL,
  SERVER_REVALIDATE,
  FILE_VISIT_HOSTNAME: _OSS_HOSTNAME,
  SERVER_PORT: _SERVER_PORT
} = process.env;

const _SERVER_REVALIDATE = Number(SERVER_REVALIDATE);

export {
  FILE_URL,
  DOMAIN,
  HOSTNAME,
  _ADMIN_ID,
  _RENDER_MODE,
  _SERVER_URL,
  _SERVER_REVALIDATE,
  _OSS_HOSTNAME,
  _SERVER_PORT
};
